### ISSUE TITLE
Kinda works and not working

### ISSUE THREAD

**Issue by raymondtam** [memberful/apple-pay-for-stripe#1]
Sorry for the confusing title, 
When i go to `https://<my-domain>/.well-known/apple-developer-merchantid-domain-association` It gets me back a v long string with a 404. Then i go to Stripe, and try to verify the domain, it fails...

Could you give me any suggestion? I am thinking if its something about the status code.
Thanks in advanced.

PS. I am posting here, in case someone spends hours and finally bump into this great plugin but fails to get it working.

**Comment by mrhead** [comment]
Hey @raymondtam,

Did you turn on permailins in `WP Dashboard -> Settings -> Permalinks`? You have to use other settings then `Plain` in order to make it works.

Also, what is your domain? Maybe I can check it directly.

**Comment by raymondtam** [comment]
Hey, thanks for the reply. And yeah, I am using numeric for Permalinks.
the domain i am working at is

**Comment by mrhead** [comment]
It looks like an issue with your setup. The plugin is working correctly and the verification string is displayed, but your server responds with `404` status code.

I am sorry, but I can't help you here.
